export const agents = [
  {
    name: "Coletor de Dados Six Box",
    slug: "coletor-dados-six-box",
    category: "Diagnóstico",
    shortDescription: "Coleta dados estruturados para leitura inicial do cenário.",
    active: true,
  },
  {
    name: "Analista de Diagnóstico Six Box",
    slug: "analista-diagnostico-six-box",
    category: "Diagnóstico",
    shortDescription: "Analisa os dados do Six Box para identificar gaps e prioridades.",
    active: true,
  },
  {
    name: "Analista de Pesquisa de Clima",
    slug: "pesquisa-clima-organizacional",
    category: "Diagnóstico",
    shortDescription: "Analisa clima organizacional e sinais do ambiente interno.",
    active: true,
  },
{
    name: "CLT IA",
    slug: "coletor-dados-six-box",
    category: "Pesquisa",
    shortDescription: "Busca artigos da CLT em base local e responde com resumo fiel e artigo na íntegra.",
    active: true,
  },
  {
    name: "Analista de Diagnóstico Six Box",
    slug: "analista-diagnostico-six-box",
    category: "Diagnóstico",
    shortDescription: "Analisa os dados do Six Box para identificar gaps e prioridades.",
    active: true,
  },
  {
    name: "Analista de Pesquisa de Clima",
    slug: "clt-ia",
    category: "Diagnóstico",
    shortDescription: "Analisa clima organizacional e sinais do ambiente interno.",
    active: true,
  },
  {
    name: "Analista de Taxa de Produtividade por Colaborador",
    slug: "taxa-produtividade-colaborador",
    category: "Diagnóstico",
    shortDescription: "Avalia produtividade individual com visão analítica.",
    active: true,
  },
  {
    name: "Analista de Custo por Contratação",
    slug: "custo-contratacao",
    category: "Diagnóstico",
    shortDescription: "Analisa custos envolvidos no processo de contratação.",
    active: true,
  },
  {
    name: "Agente de Mapeamento de Competências",
    slug: "mapeamento-competencias",
    category: "Critérios",
    shortDescription: "Mapeia competências essenciais para a função.",
    active: true,
  },
  {
    name: "Analista de Fit Cultural",
    slug: "analista-fit-cultural",
    category: "Critérios",
    shortDescription: "Avalia aderência cultural entre candidato e empresa.",
    active: true,
  },
  {
    name: "Criador de Descrição de Cargo por Competência",
    slug: "descricao-cargo-competencia",
    category: "Critérios",
    shortDescription: "Cria descrições de cargo orientadas por competências.",
    active: true,
  },
  {
    name: "Entrevistador Automatizado",
    slug: "entrevistador-automatizado",
    category: "Recrutamento & Seleção",
    shortDescription: "Conduz entrevistas estruturadas com foco em evidências.",
    active: true,
  },
  {
    name: "Mentor de Dinâmicas",
    slug: "mentor-dinamicas",
    category: "Recrutamento & Seleção",
    shortDescription: "Sugere dinâmicas para avaliar candidatos com mais precisão.",
    active: true,
  },
  {
    name: "Teste de Perfil Comportamental",
    slug: "teste-perfil-comportamental",
    category: "Recrutamento & Seleção",
    shortDescription: "Avaliação híbrida com relatório para o recrutador.",
    active: true,
  },
  {
    name: "DISC",
    slug: "teste-perfil-disc",
    category: "Recrutamento & Seleção",
    shortDescription: "Avaliação DISC com relatório para o recrutador.",
    active: true,
  },
  {
    name: "Especialista em Taxa de Aderência com a Vaga",
    slug: "taxa-de-aderencia-com-a-vaga",
    category: "Recrutamento & Seleção",
    shortDescription: "Calcula aderência entre perfil, vaga e contexto cultural.",
    active: true,
  },
  {
    name: "Especialista em Parecer Técnico de Entrevista",
    slug: "parecer-tecnico-entrevista",
    category: "Recrutamento & Seleção",
    shortDescription: "Gera parecer técnico com base nas evidências da entrevista.",
    active: true,
  },

  {
    name: "Especialista em Taxa de Aderência com a Vaga",
    slug: "taxa-aderencia-vaga",
    category: "Recrutamento & Seleção",
    shortDescription: "Calcula aderência entre perfil, vaga e contexto cultural.",
    active: true,
  },

  {
    name: "Onboarding Estratégico",
    slug: "onboarding-estrategico",
    category: "Desenvolvimento",
    shortDescription: "Estrutura integração do colaborador com método.",
    active: true,
  },
  {
    name: "Analista de Plano de Desenvolvimento",
    slug: "analista-pdi",
    category: "Desenvolvimento",
    shortDescription: "Cria plano de desenvolvimento individual com foco prático.",
    active: true,
  },
  {
    name: "Desligamento Humanizado",
    slug: "desligamento-humanizado",
    category: "Encerramento",
    shortDescription: "Organiza o desligamento com clareza e humanização.",
    active: true,
  },
];
