export const agentsCatalog = [
  {
    slug: "teste-perfil-comportamental",
    name: "Teste de Perfil Comportamental",
    category: "Comportamento",
    shortDescription: "Análise comportamental aplicada ao RH.",
    image: "/agents/teste-perfil-comportamental-light.png",
    imageDark: "/agents/teste-perfil-comportamental-dark.png",
    creditCost: 3,
    active: true,
  },
  {
    slug: "taxa-aderencia-vaga",
    name: "Taxa de Aderência à Vaga",
    category: "Recrutamento",
    shortDescription: "Calcula aderência do candidato à vaga.",
    image: "/agents/taxa-aderencia-vaga-light.png",
    imageDark: "/agents/taxa-aderencia-vaga-dark.png",
    creditCost: 1,
    active: true,
  },
  {
    slug: "taxa-produtividade-colaborador",
    name: "Taxa de Produtividade por Colaborador",
    category: "People Analytics",
    shortDescription: "Avalia produtividade individual.",
    image: "/agents/taxa-produtividade-colaborador-light.png",
    imageDark: "/agents/taxa-produtividade-colaborador-dark.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "coletor-dados-six-box",
    name: "Coletor de Dados Six Box",
    category: "Performance",
    shortDescription: "Coleta insumos para análise Six Box.",
    image: "/agents/coletor-dados-six-box-light.png",
    imageDark: "/agents/coletor-dados-six-box-dark.png",
    creditCost: 0,
    active: true,
  },
  {
    slug: "analista-diagnostico-six-box",
    name: "Analista Diagnóstico Six Box",
    category: "Performance",
    shortDescription: "Interpreta dados do modelo Six Box.",
    image: "/agents/analista-diagnostico-six-box-light.png",
    imageDark: "/agents/analista-diagnostico-six-box-dark.png",
    creditCost: 0,
    active: true,
  },
  {
    slug: "descricao-cargo-competencia",
    name: "Descrição de Cargo por Competência",
    category: "Estruturação RH",
    shortDescription: "Gera descrição de cargo orientada por competências.",
    image: "/agents/descricao-cargo-competencia-light.png",
    imageDark: "/agents/descricao-cargo-competencia-dark.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "analista-fit-cultura",
    name: "Analista de Fit Cultural",
    category: "Recrutamento",
    shortDescription: "Analisa compatibilidade cultural.",
    image: "/agents/analista-fit-cultura-light.png",
    imageDark: "/agents/analista-fit-cultura-dark.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "mapeamento-competencias",
    name: "Mapeamento de Competências",
    category: "Estruturação RH",
    shortDescription: "Mapeia competências por função ou área.",
    image: "/agents/mapeamento-competencias-light.png",
    imageDark: "/agents/mapeamento-competencias-dark.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "mentor-dinamicas",
    name: "Mentor de Dinâmicas",
    category: "Recrutamento",
    shortDescription: "Sugere dinâmicas para selection.",
    image: "/agents/mentor-dinamicas-light.png",
    imageDark: "/agents/mentor-dinamicas-dark.png",
    creditCost: 1,
    active: true,
  },
  {
    slug: "entrevistador-automatizado",
    name: "Entrevistador Automatizado",
    category: "Recrutamento",
    shortDescription: "Cria roteiros estruturados de entrevista.",
    image: "/agents/entrevistador-automatizado-light.png",
    imageDark: "/agents/entrevistador-automatizado-dark.png",
    creditCost: 1,
    active: true,
  },
  {
    slug: "teste-perfil-disc",
    name: "Teste de Perfil DISC",
    category: "Comportamento",
    shortDescription: "Análise comportamental com DISC.",
    image: "/agents/teste-perfil-disc-light.png",
    imageDark: "/agents/teste-perfil-disc-dark.png",
    creditCost: 3,
    active: true,
  },
  {
    slug: "agente-teste-bigfive",
    name: "Agente Teste Big Five",
    category: "Comportamento",
    shortDescription: "Avaliação psicométrica baseada no Big Five.",
    image: "/agents/analista-bigfive-light.png",
    imageDark: "/agents/analista-bigfive-dark.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "analista-pdi",
    name: "Analista de PDI",
    category: "Desenvolvimento",
    shortDescription: "Estrutura plano de desenvolvimento individual.",
    image: "/agents/analista-pdi-light.png",
    imageDark: "/agents/analista-pdi-dark.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "desligamento-humanizado",
    name: "Desligamento Humanizado",
    category: "Gestão de Pessoas",
    shortDescription: "Apoia comunicação e processo de desligamento.",
    image: "/agents/desligamento-humanizado-light.png",
    imageDark: "/agents/desligamento-humanizado-dark.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "onboarding-estrategico",
    name: "Onboarding Estratégico",
    category: "Gestão de Pessoas",
    shortDescription: "Cria roteiros de integração.",
    image: "/agents/onboarding-estrategico-light.png",
    imageDark: "/agents/onboarding-estrategico-dark.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "custo-por-contratacao",
    name: "Custo por Contratação",
    category: "People Analytics",
    shortDescription: "Calcula custo por contratação.",
    image: "/agents/custo-por-contratacao-light.png",
    imageDark: "/agents/custo-por-contratacao-dark.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "pesquisa-clima-organizacional",
    name: "Pesquisa de Clima Organizacional",
    category: "Engajamento",
    shortDescription: "Estrutura pesquisas de clima.",
    image: "/agents/pesquisa-clima-organizacional-light.png",
    imageDark: "/agents/pesquisa-clima-organizacional-dark.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "parecer-tecnico-entrevista",
    name: "Parecer Técnico de Entrevista",
    category: "Recrutamento",
    shortDescription: "Gera parecer técnico pós-entrevista.",
    image: "/agents/parecer-tecnico-entrevista-light.png",
    imageDark: "/agents/parecer-tecnico-entrevista-dark.png",
    creditCost: 1,
    active: true,
  },
] as const;
