export const agentsCatalog = [
  {
    slug: "teste-perfil-comportamental",
    name: "Teste de Perfil Comportamental",
    category: "Comportamento",
    shortDescription: "Análise comportamental aplicada ao RH.",
    image: "/agents/teste-perfil-comportamental.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "taxa-aderencia-vaga",
    name: "Taxa de Aderência à Vaga",
    category: "Recrutamento",
    shortDescription: "Calcula aderência do candidato à vaga.",
    image: "/agents/taxa-aderencia-vaga.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "taxa-produtividade-colaborador",
    name: "Taxa de Produtividade por Colaborador",
    category: "People Analytics",
    shortDescription: "Avalia produtividade individual.",
    image: "/agents/taxa-produtividade-colaborador.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "coletor-dados-six-box",
    name: "Coletor de Dados Six Box",
    category: "Performance",
    shortDescription: "Coleta insumos para análise Six Box.",
    image: "/agents/coletor-dados-six-box.png",
    creditCost: 1,
    active: true,
  },
  {
    slug: "analista-diagnostico-six-box",
    name: "Analista Diagnóstico Six Box",
    category: "Performance",
    shortDescription: "Interpreta dados do modelo Six Box.",
    image: "/agents/analista-diagnostico-six-box.png",
    creditCost: 3,
    active: true,
  },
  {
    slug: "descricao-cargo-competencia",
    name: "Descrição de Cargo por Competência",
    category: "Estruturação RH",
    shortDescription: "Gera descrição de cargo orientada por competências.",
    image: "/agents/descricao-cargo-competencia.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "analista-fit-cultura",
    name: "Analista de Fit Cultural",
    category: "Recrutamento",
    shortDescription: "Analisa compatibilidade cultural.",
    image: "/agents/analista-fit-cultura.png",
    creditCost: 3,
    active: true,
  },
  {
    slug: "mapeamento-competencias",
    name: "Mapeamento de Competências",
    category: "Estruturação RH",
    shortDescription: "Mapeia competências por função ou área.",
    image: "/agents/mapeamento-competencias.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "mentor-dinamicas",
    name: "Mentor de Dinâmicas",
    category: "Recrutamento",
    shortDescription: "Sugere dinâmicas para seleção.",
    image: "/agents/mentor-dinamicas.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "entrevistador-automatizado",
    name: "Entrevistador Automatizado",
    category: "Recrutamento",
    shortDescription: "Cria roteiros estruturados de entrevista.",
    image: "/agents/entrevistador-automatizado.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "teste-perfil-disc",
    name: "Teste de Perfil DISC",
    category: "Comportamento",
    shortDescription: "Análise comportamental com DISC.",
    image: "/agents/teste-perfil-disc.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "analista-pdi",
    name: "Analista de PDI",
    category: "Desenvolvimento",
    shortDescription: "Estrutura plano de desenvolvimento individual.",
    image: "/agents/analista-pdi.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "desligamento-humanizado",
    name: "Desligamento Humanizado",
    category: "Gestão de Pessoas",
    shortDescription: "Apoia comunicação e processo de desligamento.",
    image: "/agents/desligamento-humanizado.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "onboarding-estrategico",
    name: "Onboarding Estratégico",
    category: "Gestão de Pessoas",
    shortDescription: "Cria roteiros de integração.",
    image: "/agents/onboarding-estrategico.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "custo-por-contratacao",
    name: "Custo por Contratação",
    category: "People Analytics",
    shortDescription: "Calcula custo por contratação.",
    image: "/agents/custo-por-contratacao.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "pesquisa-clima-organizacional",
    name: "Pesquisa de Clima Organizacional",
    category: "Engajamento",
    shortDescription: "Estrutura pesquisas de clima.",
    image: "/agents/pesquisa-clima-organizacional.png",
    creditCost: 2,
    active: true,
  },
  {
    slug: "parecer-tecnico-entrevista",
    name: "Parecer Técnico de Entrevista",
    category: "Recrutamento",
    shortDescription: "Gera parecer técnico pós-entrevista.",
    image: "/agents/parecer-tecnico-entrevista.png",
    creditCost: 2,
    active: true,
  },
] as const;
